HyDE-Project/HyDE

Configs/.config/wlogout/layout_1

@kRHYME7 could you test it ?
i also have this in userprefs as i use a laptop maybe we could include this in keybindings.conf and comment it so if laptop users want a "sleep mode" more similar to that windows which first calls hyprlock and then suspends so whenever we wake the system it firsts asks for password
`bindl = , XF86PowerOff, exec, hyprlock & disown && systemctl suspend # launch lock screen & suspend`

better suspend command 

---

Configs/.config/waybar/modules/cliphist.jsonc

Added the missing hyphen “ - ” to the arguments of the cliphist.sh script in the waybar module, as the missing hyphen caused the arguments to never execute when clicked.

fix typo in the script arguments call

---

Configs/.hyde.zshrc
Configs/.zshenv
Configs/.zshrc
Scripts/pkg_core.lst
Scripts/pkg_custom.lst
Scripts/restore_cfg.psv
Scripts/restore_shl.sh
Scripts/restore_zsh.lst

breaks: zshrc should manually be cleaned up or else omz will reinitialize the plugins.   
for this compromise
+ I also added a warning if loading takes up more than 3 seconds for slow PC (works on a VM) 
+ Only showed 1 time per reboot 
feat: Won't touch .zshrc
feat: easy updates for hyde
feat: User configuration
feat: can uninstall hyde without removing users zshrc
feat: put oh-my-zsh locally ($HOME)
feat: update omz on restore_shl.sh
feat: faster startup by only using single `alias` call 
fix: omz packaging issues,

breaking (zshrc): Rework for the zshrc implementation

---

Configs/.local/bin/hyde-shell
Configs/.local/lib/hyde/cava.sh
Configs/.local/lib/hyde/emoji-picker.sh
Configs/.local/lib/hyde/fastfetch.sh
Configs/.local/lib/hyde/font.sh
Configs/.local/lib/hyde/glyph-picker.sh
Configs/.local/lib/hyde/hypr.unbind.sh
Configs/.local/lib/hyde/keyboardswitch.sh
Configs/.local/lib/hyde/lockscreen.sh
Configs/.local/lib/hyde/parse.config.py
Configs/.local/lib/hyde/polkitkdeauth.sh
Configs/.local/lib/hyde/sensorsinfo.py
Configs/.local/lib/hyde/swwwallkon.sh
Configs/.local/lib/hyde/sysmonlaunch.sh
Configs/.local/lib/hyde/testrunner.sh
Configs/.local/lib/hyde/wallbash.hypr.sh
Configs/.local/lib/hyde/wallbash.print.colors.sh
Configs/.local/lib/hyde/wallbash.qt.sh
Scripts/chaotic_aur.sh
Scripts/restore_thm.sh

- This is to support modern distro. 
- We need to have a common interpreter to debug correctly
I think we can just manually link  `/bin/env`  to `/usr/bin/env`  or vice versa, just like how other distros do it. 
So my proposal will be in `install.sh` we will add a strict check if `/usr/bin/env` exist if not find it if error abort. 
But on debian12 it is /usr/bin/env is already supported. (using distrobox)
Because most of the scripts that use `sh` are actually written in  `bash`! That means there will be unpredictable stuff. And debugging is annoying. 
I would like to discuss it here @Senshi111  @rubiin @richen604 
ref: https://github.com/HyDE-Project/HyDE/discussions/149#discussioncomment-11949678

consistent shabangs

---

Configs/.hyde.zshrc
Configs/.zshenv

I notice that after update Hyde, my custom sctipts in omz wouldn't load properly.
So I bring back the OMZ loading script at the top of .hyde.zshrc
I think this should be managed by hyde if we use OMZ by defualt.

Load OMZ in .hyde.zshrc

---

Configs/.local/lib/hyde/volumecontrol.sh

- Added a mechanism to toggle volume boost using the `isVolumeBoost` flag.
- Set the default volume boost state to `false` (`isVolumeBoost=false`).
- Modified `change_volume` to conditionally apply the `--allow-boost --set-limit 150` flag for `pamixer` when volume boost is enabled.
- Updated `notify_vol` to show a volume icon capped at 100 when the volume exceeds 100.
My laptop's volume is pretty low, even at 100%, so I figured enabling volume boost would help improve it.

Added volume boost feature: Update volumecontrol.sh

---

Configs/.local/lib/hyde/wallpaper.rofi.sh
Configs/.local/lib/hyde/wallpaper.sh
Configs/.local/lib/hyde/wallselect.sh

Ref #214 
Adds the hyprlock backend and wrapper for selecting wallpaper with the `--help` option and using the `--backend` flag

[pull request]: fix typo, add `wallselect.sh` and support for the hyprlock backend

---

Configs/.local/lib/hyde/gnome-terminal
Configs/.local/lib/hyde/sysmonlaunch.sh

Add support for user to select a systom monitor with config option in ~/.config/hyde/config.toml like this.
```toml
[utils]
system_monitor = "btop"
```

Feat: Add config option for system monitor

---

Configs/.local/lib/hyde/fastfetch.sh

This is the MR for issue #282 
fastfetch.sh now has more options to choose the logo from. The following options has been added:
```
--os      Display the distro logo
--local   Display a logo inside the fastfetch logo directory
--wall    Display a logo inside the wallbash fastfetch directory
--theme   Display a logo inside the hyde theme directory
```
- If you have 4 logos inside your local map, then `fastfetch.sh logo --local --os` will 4/5 times display a logo out of your local map and 1/5 times the os logo. Not 50/50 as it was previously:  `fastfetch.sh logo --quad --rand` (as `--rand` was the only option with multiple icons inside)
- `--rand` now only works if it is directly after logo. So …

refactor fastfetch.sh: enhance logo option parsing options

---

README.md

Fix dark theme not rendering issue (#297)
Now it correctly renders for both dark and light theme instead of being light by default.
How it was:
How it is now:

Fix: README.md stars section dark theme

---

README.md
Source/docs/README.de.md
Source/docs/README.es.md
Source/docs/README.nl.md
Source/docs/README.zh.md

The wiki button in `README.md` now links to the website (https://hydeproject.pages.dev/) instead of the GitHub wiki.

Fix: Update Wiki link

---

Configs/.config/hypr/keybindings.conf

Purely a spelling/wording PR
E.g.
```
bindde = $mainMod Shift Control, left, Move activewindow to the left, exec $moveactivewindow -30 0 || hyprctl dispatch movewindow l
```
Changed to accurately reflect what the keybind is doing.
Before
After

fix: Fix spelling/wording in default keybindings

---

Configs/.zshenv

This commit changes the order of plugin loading function and alias definition in .zshenv to make the default 'ls' alias of HyDE works as expected. The original order defines the alias first before calling the function to load plugins. However, that function executes the script oh-my-zsh.sh, which in turn executes the scripts in the "lib" folder of oh-my-zsh. Some of these scripts redefine the 'ls' alias to the default of Oh My Zsh.

fix: change plugin and alias load order in .zshenv

---

Configs/.zshenv

Some package manager aliases in `.zshenv` were using the wrong `pm.sh` command and so will not work. I fixed those to the correct `pm.sh` command. I also make the `in` alias to open an interactive panel for choosing package when it is called without any argument. This makes `in` to be more parallel to `un`.

fix: fix the package manager alias

---

Configs/.local/lib/hyde/screenshot.sh

Simple refactor to `screenshot.sh`. I changed some lines for compatibility (e.g. `which` was replaced with `command -v`). A simple function was made to handle taking screenshots, as opposed to of defining the arguments inline. The usage dialog was updated to include the OCR functionality as well.

refactor: rewrite sections of screenshot.sh for maintainability

---

Configs/.local/lib/hyde/globalcontrol.sh

**Check three at the same time to save time.**
In resent update, pkg_installed was called in rofi launch script, and it is very slow when uwsm is not installed, so I parallelize it to deal with the lag.

Parallelize pkg_installed

---

Configs/.local/lib/hyde/emoji-picker.sh

Refactor emoji-picker to match the style of glyph-picker due to their similar functionality. Improves code readability and maintainability, and migrates variables to snake_case.

refactor: style match emoji-picker.sh with glyph-picker.sh

---

Configs/.local/lib/hyde/mediaplayer.py

Following #407:
- Added tooltip to `mediaplayer.py` with full song name, artist, current song position and total song duration
- No need to update `spotify.jsonc`
See below for screenshots.
**Long song name truncated + tooltip**
**Regular song, with tooltip**

style: Add tooltip to mediaplayer.py

---

Configs/.config/kitty/hyde.conf
Configs/.config/kitty/kitty.conf

feat:  add Kitty tab bar styling and add new tab shortcut
Summary of Changes:
This pull request refines the Kitty terminal's appearance with minimal tab bar styling and introduces a more intuitive keyboard shortcut (Ctrl+Shift+T) for opening a new tab in the current working directory.
Motivation and Context:
The default Kitty tab bar appearance was considered less visually appealing. This change implements a minimal styling to improve its aesthetics by placing it at the bottom, using a powerline style with slanted separators, and displaying the number of windows when relevant.
Additionally, a new keyboard shortcut (Ctrl+Shift+T) has been added to open a new tab within the current working directory. This provides a more direct and commonly expected behavior for users who frequently need to …

Enhance Kitty Tab Bar Appearance and Add "New Tab in Current Directory" Shortcut and Add commented guides  to minimize latency in kitty 

---

Configs/.config/starship/starship.toml

This PR fixes:
- single "Github Icon" displaying before $git_status when status is null! while keeping Icon when there is something to show!
(check screenshot below)
- added icons for scala and zig languages with simple formats to starship.tom
- remmoved unnecessary comments

minor modifications to main starship config

---

Configs/.config/hypr/keybindings.conf
KEYBINDINGS.md

This Pr fixes:
- previously broken and commented Alt Tab keybind in hyprland keybinds
- window size when a widnow was set to float via $Mod W (previously It filled screen and this bug was more noticable on smaller screens causing negative margins)
- typo in `KEYBINDINGS.md` [!TIP] 
and Updates:
- `KEYBINDINGS.md` adding  `<Alt-T>` accordingly!

Fix hyprland keybinds

---

Configs/.config/starship/powerline.toml
Configs/.config/starship/starship.toml

This PR adds missing supported modules to `starship.toml` config and follows same formatting and styling. Also all icons are switched to HyDE supported nerd Icons
Also all `$version` are removed from modules! since they are not convenient

Add missing modules to Starship config 

---

Configs/.zshenv

Adding _zsh_autosuggest_start to _load_post_init fixes DEFER_OMZ_LOAD causing the first prompt not to work

fix(zsh): zsh-autosuggestions won't work on first prompt when deferred

---

Configs/.local/lib/hyde/lockscreen.sh

There is no need to source `${HYDE_RUNTIME_DIR}/environment` in `lockscreen.sh` script, because it It already sourced in [`globalcontrol.sh`](https://github.com/HyDE-Project/HyDE/blob/master/Configs/.local/lib/hyde/globalcontrol.sh#L243)

fix: no need to source HyDE runtime env in `lockscreen.sh`

---

Configs/.local/lib/hyde/gamelauncher.sh

- Adds in feedback when processing steam games and if no games are found
- Handles multiple steam library images by taking the first only (Elder scrolls online has multiple...)
- Fixes the steam games header image not showing in the notification on launch
Launch notification before changes
Launch notification after changes

Gamelauncher steam header icon

---

Configs/.config/hyde/wallbash/always/discord.dcol

This PR changes the custom styling to reveal the hidden scrollbars. Observe the images with and without the scrollbars for reference. (#665) 
I understand that the margin is not needed for the scrollbars but I think it is necessary because without it, the scrollbars stick to the sides (bad UX)

fix: Missing scrollbars on Discord Clients

---

Configs/.config/hyde/wallbash/scripts/discord.sh

Sets the XDG cache home to for the cachedir param, if missing the script failed the cp steps

fix: includes the XDG cache directory in the discord wallbash script 

---

Configs/.user.zsh

Fix #677 
Limited banner loading to interactive shells since non-interactive shells typically shouldn't load graphic/ascii art, display system information, etc. Without this change, commands such as `script -c 'echo hi' /tmp/script.log` will include the output of startup commands such as `fastfetch`.

fix: Fix #677/graphic-loading for non-interactive shell

---

Scripts/uninstall.sh

Looks like this note was missed when refactoring was done. This PR changes naming of configs to actual values.

fix: change config names in `uninstall.sh` note to actual values

---

Configs/.config/hypr/keybindings.conf
KEYBINDINGS.md

`animations.sh` script does not have a default keybinding, but looks like it should have some.
This PR offers some suitable keybinding and documentation update for it.

feat: add keybinding for rofi animation select menu

---

Configs/.config/hypr/keybindings.conf
KEYBINDINGS.md

Same as PR https://github.com/HyDE-Project/HyDE/pull/698 this one adds suitable default keybinding for hyprlock layout select menu.

feat: add keybinding for hyprlock layout select menu

---

Configs/.local/lib/hyde/mediaplayer.py
Configs/.local/share/hyde/schema/config.toml
Configs/.local/share/hyde/schema/config.toml.json

Small feature for `mediaplayer.py` - ability to change separator between artist and track to any custom one.

feat: customizable separator for mediaplayer.py

---

Configs/.local/lib/hyde/mediaplayer.py

Looks like in some merge there was a mistake which leads to using undefined `separator` var.
This fix the mistake and use correct `artist_track_separator` var

fix: mediaplayer.py `artist_track_separator` refers to undefined var

---

Configs/.local/share/waybar/layouts/hyprdots/01.jsonc
Configs/.local/share/waybar/layouts/hyprdots/02.jsonc
Configs/.local/share/waybar/layouts/hyprdots/03.jsonc
Configs/.local/share/waybar/layouts/hyprdots/04.jsonc
Configs/.local/share/waybar/layouts/hyprdots/05.jsonc
Configs/.local/share/waybar/layouts/hyprdots/06.jsonc
Configs/.local/share/waybar/layouts/hyprdots/07.jsonc
Configs/.local/share/waybar/layouts/hyprdots/08.jsonc
Configs/.local/share/waybar/layouts/hyprdots/09.jsonc
Configs/.local/share/waybar/layouts/hyprdots/10.jsonc
Configs/.local/share/waybar/layouts/hyprdots/11.jsonc
Configs/.local/share/waybar/layouts/hyprdots/12.jsonc
Configs/.local/share/waybar/layouts/hyprdots/13.jsonc
Configs/.local/share/waybar/layouts/hyprdots/14.jsonc
Configs/.local/share/waybar/layouts/hyprdots/15.jsonc
Configs/.local/share/waybar/layouts/hyprdots/16.jsonc
Configs/.local/share/waybar/layouts/hyprdots/17.jsonc

As discussed here: https://github.com/HyDE-Project/HyDE/pull/215#issuecomment-2943062146
The point was to add menu closer to the corner of the bar and remove any modules which functions are duplicated by menu, if those modules are in same group.

feat: add hyde-menu module to all hyprdots-ported layouts

---

.github/workflows/ci.yml

This is second attempt to make ci gh workflow to skip forked repos. Previous was here: https://github.com/HyDE-Project/HyDE/pull/746
> [!WARNING]
> This time I also do not test anything unfortunatelly

ci: do not create automated PRs on forked repos, second attempt

---

Configs/.local/share/waybar/modules/hyprland-workspaces#kanji.jsonc
Configs/.local/share/waybar/modules/hyprland-workspaces#roman.jsonc

I had ported versions of [kanji](https://github.com/HyDE-Project/HyDE/blob/v0.3.0/Configs/.config/waybar/modules/workspaces%23%23kanji.jsonc) and [roman](https://github.com/HyDE-Project/HyDE/blob/v0.3.0/Configs/.config/waybar/modules/workspaces%23%23roman.jsonc) waybar `hyprland/workspaces` module

feat: port kanji & roman options of `hyprland/workspaces` waybar module

---

Configs/.local/lib/hyde/waybar.py

fixes infinite reload of the waybar python script because nixos is special and has special named programs :sweat_smile: 
on a sidenote i have a sed script already that replaces `killall waybar` with `.waybar-wrapped` globally, weirdly `pkill waybar` somehow works

fix: include nixos wrapped program to prevent infinite reloads

---

Configs/.local/lib/hyde/battery.sh

Fixes #829
fix script Configs/.local/lib/hyde/battery.sh:
- Dynamically detect any BAT* (BAT0, BAT1, etc.) instead of hardcoding BAT0
- Support systems with non-standard battery numbering
- Expand charging icons to 11 levels
- Hardcoded battery name (BAT0): The script always uses BAT0 when querying battery status/icons, but on my system the battery is named BAT1
charging_icons array overflow
- The charging_icons array is defined with only 7 elements (for 0%, 10%, …, 60%). If the battery level exceeds 60%, the script computes an index beyond the end of the array and throws an empty icon.

make battery detection dynamic and improve icon support

---

Configs/.local/share/waybar/menus/power.xml
Configs/.local/share/waybar/modules/custom-power.jsonc
Configs/.local/share/waybar/modules/custom-powermenu.jsonc

This PR offers a feature for rebooting to UEFI settings from waybar power menu.
Also it fixes IDs of power menu, because IDs with underscore do not match menu actions names in waybar modules and do not work.

feat: add `reboot to UEFI` to waybar power menu

---

Configs/.local/share/waybar/modules/custom-spotify.jsonc

Small fix which add missing whitespace. This fixes shuffle toggle for spotify.

fix: add missing whitespace in shuffle menu entry for spotify waybar module

---

Configs/.local/lib/hyde/hyprlock.sh

This PR fixes flaky bug when sometimes if hyprlock was launched using uwsm, after unlocking hyprlock is started again forcing user to unlock one more time. 
Maybe bug is related to `Restart=on-failure` option in unit file used by uwsm and non-zero exit code by hyprlock, but I can not reproduce the bug stable enough.
Solution is not to use uwsm for launching hyprlock, if uwsm is not used - bug is not present in any scenarios.

fix: do not use uwsm for hyprlock

---

Configs/.config/zsh/conf.d/hyde/terminal.zsh
Scripts/restore_cfg.psv

This fixes an error on shell start:
```
/home/zee/.config/zsh/conf.d/hyde/terminal.zsh:source:181: no such file or directory: /home/zee/.config/zsh/prompt.zsh
```

fix: add `prompt.zsh` to config restore list

---

Configs/.local/lib/hyde/screenshot.sh

This is just a copy of https://github.com/HyDE-Project/HyDE/pull/1049
Looks like commit was dropeed in recent merges and area screenshot isn't working again

fix: adapt `screenshot.sh` for updated grimblast script

---

Configs/.local/share/waybar/modules/custom-dunst.jsonc

Fix waybar `custom-dunst.jsonc` module bug which is introduced in commit `086144f`.

fix: waybar dunst module doesn't show up

---

Scripts/install.sh
Scripts/migrations/v25.8.2.sh
migrations/20250814.sh
migrations/20250815.sh

as discussed on  the discussion https://github.com/HyDE-Project/HyDE/discussions/1119
- Make sure to make PR against dev and not the master

feat: migrations

---

Configs/.local/share/hypr/windowrules.conf

Small simplification of window rules for `xdg-desktop-portal-gtk`. These is no need to explicitly add `float` rule because window will be floating from `common-popups` tag rules

fix: simplify window rules for `xdg-desktop-portal-gtk`
