HyDE-Project/HyDE

- Configs/.config/fastfetch/config.jsonc
> Feat: Enhanced Fastfetch

- Scripts/restore_cfg.lst
include animations folder --  resolve line 11 error on animations.conf
> Include animations folder 

- Configs/.config/hypr/hyprland.conf
first time making a pull request, don't mind if i make a mistake.
> fix globbing error at line 31

- README.md
> updating README to reflect the new file name

- Configs/.local/lib/hyde/sysmonlaunch.sh
> fix: small fix sysmonlaunch

- Configs/.config/waybar/modules/cava.jsonc
- Configs/.local/lib/hyde/cava.sh
- Configs/.local/lib/hyde/glyph-picker.sh
- Configs/.local/lib/hyde/hyprlock.sh
- Configs/.local/share/hyde/config.toml
- Configs/.local/share/hyde/hyprlock.conf
breaking: move waybar.cava.sh to cava.sh to reuse cava
feat: mpris  icon dictionary
fix: some
closes https://github.com/HyDE-Project/HyDE/issues/37
> hyprlock mpris icons and some cava stuff

- Scripts/restore_cfg.psv
@kRHYME7 a issue i faced while installation i hope this isnt a big change lol
> pokemon-colorscripts-git is optional and shouldnt be needed

- Configs/.local/lib/hyde/screenshot.sh
@kRHYME7 the monitor screenshots were not working only snip one worked
is this correct now ?
> fix monitor screenshot in screenshot.sh

- Configs/.config/waybar/modules/github_hyde.jsonc
With this you will be sent to the Hyde repository quickly with one click
> HyDE repository icon

- Configs/.config/waybar/modules/keybindhint.jsonc
a detail that just by putting the mouse you will see what that icon is for
> tooltip-format keybindhint.jsonc

- README.es.md
> README.es.md

- README.es.md
Now users will be sent to KEYBINDINGS.es.md sorry
> KEYBINDINGS.es.md

- Configs/.zshrc
This way all the terminals that support kitty image protocol would work without any issue
> feat: make fastfetch spit image in kitty protocol

- Configs/.config/waybar/modules/backlight.jsonc
> tooltip-format backlight.jsonc

- Source/docs/README.es.md
imagenes png de distribuciones
>  README.es.md

- Source/docs/README.es.md
> README.es.md fixed

- Configs/.config/waybar/modules/window.jsonc
spotify free and spotify premium
> window.jsonc

- Configs/.config/fastfetch/config.jsonc
> fixed: fastfetch memory icon

- Configs/.config/hypr/keybindings.conf
is this okay? it works.
closes #90
> fix: broken keybinding caused by stray commas 

- Configs/.config/waybar/modules/idle_inhibitor.jsonc
This would be great in hydedots, the idea is not mine
> caffeine mode

- Scripts/pkg_custom.lst
Lutris is an open source gaming platform for Linux.
> lutris added

- Configs/.local/lib/hyde/rofiselect.sh
- Configs/.local/lib/hyde/swwwallselect.sh
- Configs/.local/lib/hyde/themeselect.sh
Fixes #124 
Please feel free to modify, refactor, or do as you see fit to the proposed code. Fixed scripts were tested and function as expected.
> fix: rofi theming

- Configs/.local/lib/hyde/swwwallbash.sh
fixes a small typo in swwwallbash.sh. potential fix for #117 as well
> [Improvement]: minor typo fix

- Configs/.local/lib/hyde/weather.py
- Configs/.local/share/hyde/config.toml
> feat: Add weather location

- Configs/.local/lib/hyde/amdgpu.py
- Configs/.local/lib/hyde/keybinds.hint.py
- Configs/.local/lib/hyde/mediaplayer.py
- Configs/.local/lib/hyde/notifications.py
- Configs/.local/lib/hyde/parse.json.py
- Configs/.local/lib/hyde/parse.toml.py
- Configs/.local/lib/hyde/weather.py
-  Missing timeout argument for method 'requests.get' can cause your program to hang indefinitely
Solution adding a timeout of 10s to finish process in case of unfetching data
- 'subprocess.run' used without explicitly defining the value for 'check'.
When using subprocess.run, it's a good practice to explicitly define the check parameter to ensure that the function behaves as expected. The check parameter, when set to True, will raise a CalledProcessError if the command exits with a non-zero status.
- Use lazy % formatting in logging functions
This way, the actual string formatting is deferred until it is necessary, which can improve performance.
- E1310:bad-str-strip-call
The error E1310:bad-str-strip-call indicates that the argument passed to str.strip is suspicious. The strip method is …
> warning handling python scripts

- Configs/.zshenv
Sets xdg compliant folders
more here
https://wiki.archlinux.org/title/XDG_Base_Directory
> feat(zshenv): add environment variables for home folder organization

- .github/ISSUE_TEMPLATE/bug_report.es.md
- .github/ISSUE_TEMPLATE/custom.es.md
- .github/ISSUE_TEMPLATE/custom.md
- .github/ISSUE_TEMPLATE/documentation_update.es.md
- .github/ISSUE_TEMPLATE/feature_request.es.md
- .github/PULL_REQUEST_TEMPLATE.es.md
> translation 

- KEYBINDINGS.md
- Source/docs/KEYBINDINGS.de.md
- Source/docs/KEYBINDINGS.es.md
- Source/docs/KEYBINDINGS.zh.md
- Source/docs/README.zh.md
> Translate keybindings.md to Chinese

- Configs/.local/share/hyde/wallbash/scripts/dunst.sh
remove dunstctl and add killall; dunst & back again
> Fix dunst on response

- Configs/.zshenv
Tested.
Ready to go.
see #243 for more info.
> Load zshenv script for usage out of terminal

- Hyprdots-to-HyDE.md
This adds a possible and most likely meaning to the naming "HyDE".
> Update the meaning of HyDE in Hyprdots-to-HyDE.md

- KEYBINDINGS.md
- README.md
- Source/docs/KEYBINDINGS.de.md
- Source/docs/KEYBINDINGS.es.md
- Source/docs/KEYBINDINGS.nl.md
- Source/docs/KEYBINDINGS.zh.md
- Source/docs/README.de.md
- Source/docs/README.es.md
- Source/docs/README.nl.md
- Source/docs/README.zh.md
closes #273 
- Dutch translation for README.md and KEYBINDINGS.md. 
- I also fixed some mistakes I found while translating, like missing components and broken links.
- [x ] **Documentation update** (non-breaking change; modified files are limited to the documentations)
- [x ] I have read the [CONTRIBUTING](https://github.com/prasanthrangan/hyprdots/blob/main/CONTRIBUTING.md) document.
- [x ] My code follows the code style of this project.
- [ x] My commit message follows the [commit guidelines](https://github.com/prasanthrangan/hyprdots/blob/main/CONTRIBUTING.md#git-commit-messages).
- [ x] My change requires a change to the documentation.
- [ x] I have updated the documentation accordingly.
- [ x] I …
> Dutch Documentation

- README.md
- Source/docs/README.de.md
- Source/docs/README.es.md
- Source/docs/README.nl.md
- Source/docs/README.zh.md
I made some small layout changes:
- Gap between title and line is smaller
- Included a gap between the video and installation title.
Before:
After:
(font size did not change, it looks like this happened because my screenshots were in windows of different sizes)
If the changes are approved, I will change the README files in other languages similarly.
> Readme layout update

- Configs/.local/bin/hyde-shell
- Configs/.local/lib/hyde/keybinds.hint.py
- Configs/.local/lib/hyde/sensorsinfo.py
- Configs/.local/lib/hyde/weather.py
- Improved wttr.in data fetchin + name parisng to snake_case
- subprocess.run check handling
- imporve performance in array iterations
- fixed an unassigned use of a variable
- add utf-8 encoding as default
> Minor fixes 

- Source/docs/KEYBINDINGS.zh.md
- Source/docs/README.zh.md
Update README.zh.md and Keybindings.zh.md.
Ready to merge.
> Update Chinese Docs

- Configs/.local/lib/hyde/fzf_preview.sh
- Configs/.local/lib/hyde/fzf_wrapper.py
- Configs/.local/lib/hyde/theme.import.py
- Configs/.local/lib/hyde/theme.patch.sh
- Scripts/pkg_core.lst
- Replaces Hyde theme import 
- Requires fzf as core package (nothing beats fzf as of the moment in terms of usability and features)
https://github.com/HyDE-Project/HyDE/issues/169#issuecomment-2690783406 #169
https://github.com/user-attachments/assets/4185a36f-f215-4431-8b7d-654ad159f937
Ready for merging
> Hyde theme import

- Configs/.local/lib/hyde/emoji-picker.sh
Fixed Emoji Picker Adding Any Text You Put In Emoji Picker And Press Enter Like This
> Fixed Emoji Picker Injecting Random Words In Recent

- Configs/.local/lib/hyde/parse.config.py
- Configs/.local/lib/hyde/parse.json.py
- Configs/.local/lib/hyde/pyutils/compositor.py
- Configs/.local/lib/hyde/pyutils/configuration.py
- Configs/.local/lib/hyde/pyutils/logger.py
- Configs/.local/lib/hyde/pyutils/pip_env.py
- Configs/.local/lib/hyde/pyutils/requirements.txt
- Configs/.local/lib/hyde/pyutils/wrapper/fzf.py
- Configs/.local/lib/hyde/pyutils/wrapper/libnotify.py
- Configs/.local/lib/hyde/pyutils/wrapper/rofi.py
- Configs/.local/lib/hyde/pyutils/xdg_base_dirs.py
- Configs/.local/lib/hyde/theme.import.py
Features:
This is to comply to future implementation of Hydebar/hydepanel. I want it to be installed in a virtual environment to avoid mangling with the system.
HyDEs requirments.text will be inside ./pyutils/*. Includes `loguro` for  logging and `hyprpy` for hyprland pythonic interface. 
includes:
1. libnotify to have a pythonic notify-send method
2. fzf for implementing TUI prompts
3. rofi for easier rofi command handling
This is not a breaking implementation, But this serves as backbone implementation for #215 
- Uses loguru if installed and fallback to logging
- `LOG_LEVEL=debug` to enable debugging
https://github.com/HyDE-Project/HyDE/discussions/236
As requested by @dieBakterie 
#215
https://github.com/user-attachments/assets/aa02774a-e0ac-4bd2-83b0-feaaf3fdd011
> Builtin pyutils

- Hyprdots-to-HyDE.md
- Source/docs/Hyprdots-to-HyDE.zh.md
- Source/docs/README.zh.md
> [Doc]: Translate hyprdots-to-HyDE.md to Chinese

- Hyprdots-to-HyDE.md
- Source/docs/COMMIT_MESSAGE_GUIDELINES.es.md
- Source/docs/CONTRIBUTING.es.md
- Source/docs/Hyprdots-to-HyDE.es.md
This Pull Request updates the Spanish documentation to facilitate understanding for Spanish-speaking users.
> Update spanish docs

- KEYBINDINGS.md
- README.md
- Source/docs/KEYBINDINGS.ar.md
- Source/docs/KEYBINDINGS.de.md
- Source/docs/KEYBINDINGS.es.md
- Source/docs/KEYBINDINGS.fr.md
- Source/docs/KEYBINDINGS.nl.md
- Source/docs/KEYBINDINGS.zh.md
- Source/docs/README.ar.md
- Source/docs/README.de.md
- Source/docs/README.es.md
- Source/docs/README.fr.md
- Source/docs/README.nl.md
- Source/docs/README.zh.md
updates the project documentation to include support for the Arabic language, making the information more accessible to Arabic-speaking users. No changes were made to the core functionality or codebase.
- Added Arabic language support to the documentation.
- Improved clarity and structure for better readability.
- Ensured consistency across all language versions.
- This update does not affect the project's performance or functionality.
- No code modifications or bug fixes were made—changes are limited to documentation only.
> Docs: Add Arabic language support to Docs

- Scripts/pkg_core.lst
- Scripts/pkg_extra.lst
This commit will:
- Remove declaration of packages that are no longer needed
- Remove the declaration of deprecated packages
- Make the code clearer
> refactor: Cleanup deprecated & unused pkg names

- Configs/.hyde.zshrc
- Configs/.zshenv
- Configs/.zshrc
This commit will:
- fix some typos in zsh files
> fix: A few typos

- Hyprdots-to-HyDE.md
- README.md
- Source/docs/Hyprdots-to-HyDE.de.md
- Source/docs/Hyprdots-to-HyDE.es.md
- Source/docs/Hyprdots-to-HyDE.zh.md
- Source/docs/KEYBINDINGS.ar.md
- Source/docs/KEYBINDINGS.de.md
- Source/docs/KEYBINDINGS.es.md
- Source/docs/KEYBINDINGS.fr.md
- Source/docs/KEYBINDINGS.nl.md
- Source/docs/KEYBINDINGS.zh.md
- Source/docs/README.ar.md
- Source/docs/README.de.md
- Source/docs/README.es.md
- Source/docs/README.fr.md
- Source/docs/README.nl.md
- Source/docs/README.zh.md
Added and updated localisation "links" and files. Fixed typos and wrong hypertext-links and some more small changes.
> [pull-request]: fixes for localisation and other minor issues

- Configs/.config/hypr/nvidia.conf
- Adds hints in comments to fix potential lag in external monitor for a multi-GPU setup.
- I was facing lag in external monitor because of having a multi-GPU setup, and there are many different similar issues arising from other reasons so it was hard to debug.
> docs: Add hints for fixing lag in external monitor for multi-gpu setup

- Configs/.local/lib/hyde/rofilaunch.sh
Remove pkg_installed check, and change rofi command, use sh to avoid rofi throw out the error of command not found.
Tested, ready to merge.
> Optimize rofilaunch script

- Configs/.local/lib/hyde/glyph-picker.sh
Improvements to variable naming, structuring, and formatting. Hopefully makes things easier to read and maintain. Migrates vars to snake_case.
> refactor: refactor glyph-picker.sh for maintainability

- Configs/.local/lib/hyde/cliphist.sh
Refactoring of `cliphist.sh`. Matches the style of already refactored scripts and migrates variables to snake_case. This is part of an ongoing effort to refactor relevant helper scripts. If any unexpected behavior occurs during script execution, please let me know. If you have questions/comments, please let me know.
> refactor: cliphist.sh for readability and maintainability.

- README.md
This PR removes an extra space character in the README.
> docs: remove extra space

- CONTRIBUTORS.md
Hi!
I've contributed several improvements to both the **HyDE** and the **HyDE documentation site**, focusing on **internationalization (i18n)**, **user environment configuration**, and **developer experience**. 
I'm excited to keep helping the project grow, especially in improving accessibility and multilingual support.
---
- [#318](https://github.com/HyDE-Project/HyDE/pull/318): Added full French translation across the documentation.
- [#388](https://github.com/HyDE-Project/HyDE/issues/388): Raised critical issue about default aliases breaking standard commands.
- [#437](https://github.com/HyDE-Project/HyDE/pull/437): Fixed hardcoded `$HOME/Pictures` paths by using `xdg-user-dir` to respect user-defined XDG directories (WIP).
- [#10](https://github.com/HyDE-Project/hyde-site/pull/10): …
> feat: add @Metalhearf to the Collaborators list

- Configs/.config/fish/config.fish
- Configs/.zshenv
- Scripts/pkg_core.lst
This PR adds [bat](https://github.com/sharkdp/bat) to core packages
and Includes `fzf` integration with both `zsh` and `fish` (since fzf is alrady included in core packages!)
left side :
```bash
bat --style=full .zshen
```
`bat -p ...` or `bat --style=plain ...` is used for cat ailias to keep piped operations/commands intact.
eg: `cat xx | rg "smething"`
> Add `bat` and include `fzf` integration

- Configs/.config/hyde/wallbash/always/discord.dcol
Fixed the text highlight colors where the highlighted text's background was indistinguishable
Fixed colors of some buttons appearing odd
Removed **settingsicon** because it was not displayed correctly
These changes are only to make discord look nice.
better wallbash theming
> style: discord dcol file changes

- CONTRIBUTORS.md
- I've opened PRs here and there!
- Merged a line or two !
- participated in discussions and issues (@kRHYME7 that nvim-kitty padding one 😄)
- I'm the one @kRHYME7 balmes everytime people's `starship` config breaks! 
> Include in the PR description your relevant experience
- I hate `bash` but I guess it doesn't mean I can't script (i hope!)
- I can do `go` and `rust` (i think!)
- I know my way around `lua` and "actual" `nvim` configurations (iguess!)
- I love `git rebase -i --root` 🥱🥱
------
> and what you hope to contribute
- more `wallbash` integrations
- add HyDE `nvim` configuration
- populate `core packages` (@kRHYME7 i'm joking bro XD)
- put more tarrifs on china I mean `p10k`
seriously tho, 
I'd love to contribute more on `terminal-based` side of the repo, as HyDE is descripbed in …
> updated CONTRIBUTORS

- Configs/.config/hyde/wallbash/always/discord.dcol
Same thing as my last PR, but i missed one thing
Credit:-  [/home/dim](https://github.com/dim-ghub)
discord theming 
> fixed the link color being same as normal text

- CONTRIBUTORS.md
- Configs/.config/hypr/keybindings.conf
##
As the game launcher is fixed now on dev, this keybind should be re-introduced to make use of the script.
> Add keybind for game launcher

- Scripts/pkg_extra.lst
power-profile-daemon does not get installed by default on minimal arch installation.
and waybar modules needs it to function properly
this Pull Request is to add power-profile-daemon as optional package
> chore: added power profile daemon package

- Configs/.local/lib/hyde/gamelauncher.sh
Steam based game launcher wouldn't populate if you had more than one steam library. Some games also had the library image in folders other than the root. This aims to correct that
Game launcher prior to changes (I have 4 drives containing steam games)
After changes
> feat: support multiple steam libs and non standard location lib images

- Source/docs/README.ar.md
- Source/docs/README.de.md
- Source/docs/README.es.md
- Source/docs/README.fr.md
- Source/docs/README.nl.md
- Source/docs/README.pt-br.md
- Source/docs/README.zh.md
This pull request adds a complete Portuguese (pt-BR) translation of the README file.
Changes include:
- New file: `README.pt-br.md` containing the full translation.
- Add: Added badges in other README files to prominently link to the pt-BR translation.
> docs: add Portuguese (pt-BR) translation of README

- Configs/.config/hypr/windowrules.conf
> feat: skip idle inhibit for fullscreen apps

- Configs/.zshenv
- Configs/.zshrc
…hyde.zshrc
- [ x] **Other** (provide details below)
- [ x] I have read the [CONTRIBUTING](https://github.com/prasanthrangan/hyprdots/blob/main/CONTRIBUTING.md) document.
- [ x] My code follows the code style of this project.
- [x ] My commit …
> config: update .zshrc and .zshenv to reference .user.zsh instead of .hyde.zshrc

- Configs/.config/starship/starship.toml
- Make sure to make PR against dev and not the master
> fix: fix issue 708: typos in starship config

- .github/PULL_REQUEST_TEMPLATE.md
https://github.com/HyDE-Project/HyDE/issues/713
- Make sure to make PR against dev and not the master
> fix: fix issue 713

- Configs/.local/share/waybar/modules/wlr-taskbar.jsonc
Small improvement of waybar wlr/taskbar module tooltip format to make it more easy to read
> fix: waybar wlr/taskbar tooltip now more readable

- Configs/.config/zsh/conf.d/hyde/terminal.zsh
- Configs/.config/zsh/functions/bat.zsh
- Configs/.config/zsh/functions/duf.zsh
- Configs/.config/zsh/functions/eza.zsh
- Configs/.config/zsh/functions/fzf.zsh
- Scripts/pkg_core.lst
- Scripts/pkg_extra.lst
This PR is zsh-only version of https://github.com/HyDE-Project/HyDE/pull/822, but with respect to new zsh config architecture
> feat: use `bat` as replace for `cat` using new zsh architecture

- Configs/.local/share/hyde/wallbash/theme/kvantum/kvantum.dcol
fixes https://github.com/HyDE-Project/HyDE/issues/840
before:-
after:-
> fix: unreadable highlight color in dolphin

- Configs/.config/zsh/conf.d/hyde/env.zsh
- Configs/.config/zsh/conf.d/hyde/terminal.zsh
- Configs/.config/zsh/functions/bat.zsh
- Configs/.config/zsh/user.zsh
- Make OMZ optional
- Fix issue with bat global alias #910 
- Minor typo fixes
> Make OMZ optional

- Configs/.local/lib/hyde/globalcontrol.sh
Find symlinked themes. Probably a similar fix is needed for other scripts that use find
> Find symlinked themes

- Scripts/hydevm/hydevm.sh
updated the archbox url to latest, this update is a required merge for hydevm to continue working
> fix: updated url for latest archbox

- Scripts/hydevm/hydevm.sh
few changes copilot recommended in the current PR to master
- always fetch latest archbox
- bind http server to localhost
> fix(hydevm): get latest archbox, bind http server to localhost

- Configs/.config/hyde/config.toml
- Make sure to make PR against dev and not the master
> fix: add schema on config.toml
